#!/usr/bin/env python3
"""Build the single-file `cgr.py` artifact from source assets."""

from __future__ import annotations

import argparse
import ast
from pathlib import Path


VISUALIZER_MARKER = "GENERATED: VISUALIZER TEMPLATE"
IDE_MARKER = "GENERATED: EMBEDDED IDE HTML"


def _replace_marked_section(content: str, marker: str, replacement: str) -> str:
    begin = f"# BEGIN {marker}"
    end = f"# END {marker}"
    start = content.find(begin)
    if start < 0:
        raise ValueError(f"Missing marker start: {begin}")
    finish = content.find(end, start)
    if finish < 0:
        raise ValueError(f"Missing marker end: {end}")
    finish += len(end)
    if finish < len(content) and content[finish] == "\n":
        finish += 1
    return content[:start] + replacement.rstrip() + "\n" + content[finish:]


def _load_visualizer_function(path: Path) -> str:
    source = path.read_text()
    module = ast.parse(source, filename=str(path))
    lines = source.splitlines()
    for node in module.body:
        if isinstance(node, ast.FunctionDef) and node.name == "generate_html":
            fn_lines = lines[node.lineno - 1:node.end_lineno]
            fn_source = "\n".join(fn_lines) + "\n"
            return fn_source.replace("def generate_html(", "def _build_html(", 1)
    raise ValueError(f"generate_html() not found in {path}")


def _render_visualizer_section(path: Path) -> str:
    fn_source = _load_visualizer_function(path).rstrip()
    return "\n".join([
        f"# BEGIN {VISUALIZER_MARKER}",
        f"# Generated by build_cgr.py from {path.name}. Do not edit by hand.",
        fn_source,
        f"# END {VISUALIZER_MARKER}",
    ])


def _render_ide_section(path: Path) -> str:
    html = path.read_text()
    return "\n".join([
        f"# BEGIN {IDE_MARKER}",
        f"# Generated by build_cgr.py from {path.name}. Do not edit by hand.",
        f"_EMBEDDED_IDE_HTML = {html!r}",
        f"# END {IDE_MARKER}",
    ])


def build(target: Path, visualizer: Path, ide: Path) -> str:
    content = target.read_text()
    content = _replace_marked_section(content, VISUALIZER_MARKER, _render_visualizer_section(visualizer))
    content = _replace_marked_section(content, IDE_MARKER, _render_ide_section(ide))
    return content


def main() -> int:
    root = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description="Regenerate the single-file cgr.py artifact.")
    parser.add_argument("--target", default=str(root / "cgr.py"), help="Path to the target cgr.py file")
    parser.add_argument("--visualizer", default=str(root / "visualize_template.py"),
                        help="Path to the visualizer source file")
    parser.add_argument("--ide", default=str(root / "ide.html"), help="Path to the IDE HTML source file")
    parser.add_argument("--check", action="store_true",
                        help="Exit non-zero if the target is out of date; do not write files")
    args = parser.parse_args()

    target = Path(args.target)
    rendered = build(target, Path(args.visualizer), Path(args.ide))
    current = target.read_text()

    if args.check:
        if current != rendered:
            print(f"{target} is out of date. Run `python3 build_cgr.py`.")
            return 1
        print(f"{target} is up to date.")
        return 0

    if current != rendered:
        target.write_text(rendered)
        print(f"Updated {target}")
    else:
        print(f"{target} already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
